name: Terraform Plan & Compliance Check

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - '**/*.tf'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan.out

      - name: Policy Check - instance_type
        run: |
          if grep -r 'instance_type' *.tf | grep -v '"t3.micro"' ; then
            echo "❌ ERROR: Only t3.micro is allowed for EC2 instances."
            exit 1
          fi

      - name: Required Tags Check
        run: |
          REQUIRED_TAGS=("Environment" "Owner" "CostCenter")
          for TAG in "${REQUIRED_TAGS[@]}"; do
            grep -q "$TAG" *.tf || {
              echo "❌ Missing required tag: $TAG"
              exit 1
            }
          done

      - name: Slack Notification - Plan Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C090BQ2D5C3
          payload: |
            {
              "text": ":white_check_mark: *Terraform Plan Completed Successfully*\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Pushed by:* ${{ github.actor }}\n\n:bulb: Please [create a Pull Request](https://github.com/${{ github.repository }}/compare/main...${{ github.ref_name }}) to start the approval process.",
              "unfurl_links": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack Notification - Plan Failed
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: C090BQ2D5C3
          payload: |
            {
              "text": ":x: *Terraform Plan Failed!*\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Triggered by:* ${{ github.actor }}\n\nPlease review the GitHub Actions log for errors.",
              "unfurl_links": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
